export const categories = [
  {
    id: "search",
    name: "Search Engines",
    icon: "🔍",
    description: "Traditional web search without AI-generated results or chatbots",
    apps: [
      { name: "SearXNG", url: "https://searxng.org", license: "open-source", description: "Self-hosted meta-search engine aggregating results from multiple sources", replaces: "Google Search, Perplexity AI" },
      { name: "Marginalia", url: "https://search.marginalia.nu", license: "open-source", description: "Search engine focused on non-JS, non-AI web content", replaces: "AI-powered search results" },
      { name: "Wiby", url: "https://wiby.me", license: "closed-source", description: "Search engine for the classic web — hand-crafted results", replaces: "AI-curated search" },
      { name: "Mojeek", url: "https://mojeek.com", license: "closed-source", description: "Independent search engine with its own crawler, no AI ranking", replaces: "Google, Bing AI search" },
      { name: "Stract", url: "https://stract.com", license: "open-source", description: "Open-source search engine with transparent ranking", replaces: "AI search assistants" },
      { name: "DuckDuckGo", url: "https://duckduckgo.com", license: "closed-source", description: "Privacy-first search engine (non-AI instant answers mode)", replaces: "Google Search AI" },
    ],
  },
  {
    id: "browsers",
    name: "Browsers",
    icon: "🌐",
    description: "Web browsers without built-in AI assistants or AI features",
    apps: [
      { name: "Firefox", url: "https://mozilla.org/firefox", license: "open-source", description: "Full-featured browser with no built-in AI assistant", replaces: "Arc browser, Edge Copilot" },
      { name: "LibreWolf", url: "https://librewolf.net", license: "open-source", description: "Privacy-hardened Firefox fork — telemetry and AI features stripped", replaces: "AI-integrated browsers" },
      { name: "Pale Moon", url: "https://palemoon.org", license: "open-source", description: "Goanna-based browser focused on efficiency and customization", replaces: "Chrome with AI features" },
      { name: "SeaMonkey", url: "https://seamonkey-project.org", license: "open-source", description: "All-in-one internet suite — browser, email, editor, chat", replaces: "AI-ified browsers" },
      { name: "Ungoogled Chromium", url: "https://ungoogled-software.github.io", license: "open-source", description: "Chromium stripped of Google services and AI features", replaces: "Google Chrome, Edge" },
    ],
  },
  {
    id: "photo-editing",
    name: "Photo Editing",
    icon: "🎨",
    description: "Image editors using traditional tools, no AI generation or upscaling",
    apps: [
      { name: "GIMP", url: "https://gimp.org", license: "open-source", description: "Full-featured raster graphics editor — layers, masks, filters", replaces: "Adobe Photoshop AI, Canva AI" },
      { name: "Krita", url: "https://krita.org", license: "open-source", description: "Professional digital painting and photo editing", replaces: "AI image generators, Photoshop AI" },
      { name: "Darktable", url: "https://darktable.org", license: "open-source", description: "RAW photo workflow and editing — non-destructive, no AI", replaces: "Adobe Lightroom AI" },
      { name: "RawTherapee", url: "https://rawtherapee.com", license: "open-source", description: "Cross-platform RAW photo processor with manual controls", replaces: "AI photo enhancement" },
      { name: "Inkscape", url: "https://inkscape.org", license: "open-source", description: "Vector graphics editor for illustrations and diagrams", replaces: "Adobe Illustrator AI" },
      { name: "Paint.NET", url: "https://getpaint.net", license: "closed-source", description: "Lightweight image and photo editor for Windows", replaces: "Photoshop, AI editors" },
      { name: "Photopea", url: "https://photopea.com", license: "closed-source", description: "Browser-based image editor with PSD support, no AI features", replaces: "Photoshop AI, Canva AI" },
    ],
  },
  {
    id: "video-editing",
    name: "Video Editing",
    icon: "🎬",
    description: "Video editors with manual editing — no AI generation or auto-editing",
    apps: [
      { name: "DaVinci Resolve", url: "https://blackmagicdesign.com/products/davinciresolve", license: "closed-source", description: "Professional color grading and video editing (use without AI features)", replaces: "AI video editors, Runway" },
      { name: "Kdenlive", url: "https://kdenlive.org", license: "open-source", description: "Full-featured non-linear video editor for Linux and Windows", replaces: "AI auto-editing tools" },
      { name: "Olive", url: "https://olivevideoeditor.org", license: "open-source", description: "Professional open-source non-linear video editor", replaces: "Premiere Pro AI, Final Cut AI" },
      { name: "Shotcut", url: "https://shotcut.org", license: "open-source", description: "Cross-platform video editor with wide format support", replaces: "AI video generation" },
      { name: "Avidemux", url: "https://avidemux.org", license: "open-source", description: "Simple video cutting, filtering and encoding tool", replaces: "AI video tools" },
    ],
  },
  {
    id: "code-editors",
    name: "Code Editors",
    icon: "💻",
    description: "Code editors and IDEs without AI code completion or generation",
    apps: [
      { name: "VSCodium", url: "https://vscodium.com", license: "open-source", description: "VS Code fork without telemetry and Microsoft AI features", replaces: "VS Code Copilot, Cursor" },
      { name: "Neovim", url: "https://neovim.io", license: "open-source", description: "Modern Vim fork — extensible, fast, no AI baked in", replaces: "AI code assistants" },
      { name: "Geany", url: "https://geany.org", license: "open-source", description: "Lightweight IDE with basic editing, no AI features", replaces: "Copilot-enabled editors" },
      { name: "Kate", url: "https://kate-editor.org", license: "open-source", description: "KDE advanced text editor with IDE features", replaces: "AI coding assistants" },
      { name: "Emacs", url: "https://gnu.org/software/emacs", license: "open-source", description: "Extensible text editor — add only the features you need", replaces: "Cursor, Copilot-based editors" },
      { name: "Sublime Text", url: "https://sublimetext.com", license: "closed-source", description: "Fast, lightweight code editor (disable AI plugins)", replaces: "AI-powered code editors" },
    ],
  },
  {
    id: "office",
    name: "Office & Productivity",
    icon: "📄",
    description: "Office suites and productivity tools without AI assistants or AI generation",
    apps: [
      { name: "LibreOffice", url: "https://libreoffice.org", license: "open-source", description: "Full office suite — documents, spreadsheets, presentations", replaces: "Microsoft 365 AI Copilot" },
      { name: "OnlyOffice", url: "https://onlyoffice.com", license: "open-source", description: "Office suite with deep document compatibility", replaces: "Google Docs AI, Office AI" },
      { name: "FreeOffice", url: "https://freeoffice.com", license: "closed-source", description: "Microsoft Office-compatible suite, no AI features", replaces: "Office 365 AI assistant" },
      { name: "Zathura", url: "https://pwmt.org/projects/zathura", license: "open-source", description: "Minimal document viewer for PDF, EPUB, DjVu", replaces: "AI document readers" },
    ],
  },
  {
    id: "note-taking",
    name: "Note Taking",
    icon: "📝",
    description: "Note-taking apps with manual organization — no AI writing or auto-suggest",
    apps: [
      { name: "Obsidian", url: "https://obsidian.md", license: "closed-source", description: "Local-first knowledge base (disable AI plugins)", replaces: "Notion AI, Mem AI" },
      { name: "Joplin", url: "https://joplinapp.org", license: "open-source", description: "Open-source note-taking with markdown and sync", replaces: "Notion AI, AI note apps" },
      { name: "Zettlr", url: "https://zettlr.com", license: "open-source", description: "Markdown editor for academic and research writing", replaces: "AI writing assistants" },
      { name: "Trilium", url: "https://github.com/zadam/trilium", license: "open-source", description: "Self-hosted hierarchical note-taking application", replaces: "AI note-taking apps" },
      { name: "Standard Notes", url: "https://standardnotes.com", license: "open-source", description: "Encrypted note-taking, plain text (disable AI extensions)", replaces: "AI writing tools" },
    ],
  },
  {
    id: "media-players",
    name: "Media Players",
    icon: "▶️",
    description: "Media players without AI recommendations or AI-generated content",
    apps: [
      { name: "VLC", url: "https://videolan.org/vlc", license: "open-source", description: "Plays everything — no AI, no tracking, just playback", replaces: "AI-recommendation media players" },
      { name: "MPC-HC", url: "https://mpc-hc.org", license: "open-source", description: "Lightweight Windows media player, no AI features", replaces: "AI-powered media apps" },
      { name: "mpv", url: "https://mpv.io", license: "open-source", description: "Minimal powerful media player with scriptable interface", replaces: "AI-recommendation players" },
      { name: "Foobar2000", url: "https://foobar2000.org", license: "closed-source", description: "Advanced audio player with no AI features", replaces: "Spotify AI recommendations" },
      { name: "Audacious", url: "https://audacious-media-player.org", license: "open-source", description: "Lightweight audio player with Winamp-style interface", replaces: "AI music recommendation" },
    ],
  },
  {
    id: "messaging",
    name: "Messaging & Email",
    icon: "💬",
    description: "Communication tools without AI chatbots, AI replies, or AI features",
    apps: [
      { name: "Thunderbird", url: "https://thunderbird.net", license: "open-source", description: "Full-featured email client (disable AI smart replies)", replaces: "Gmail AI, Outlook AI" },
      { name: "Element", url: "https://element.io", license: "open-source", description: "Matrix client for secure decentralized messaging", replaces: "AI chatbots, Discord AI" },
      { name: "Signal", url: "https://signal.org", license: "open-source", description: "Private messaging with end-to-end encryption, no AI", replaces: "WhatsApp AI, Telegram AI" },
      { name: "Delta Chat", url: "https://delta.chat", license: "open-source", description: "Email-based messenger — uses existing email infrastructure", replaces: "AI messaging assistants" },
      { name: "SimpleX", url: "https://simplex.chat", license: "open-source", description: "Privacy-first messaging without user identifiers", replaces: "AI-integrated chat apps" },
    ],
  },
  {
    id: "password-managers",
    name: "Password Managers",
    icon: "🔐",
    description: "Password managers without AI features or AI-generated suggestions",
    apps: [
      { name: "KeePassXC", url: "https://keepassxc.org", license: "open-source", description: "Local password manager with strong encryption", replaces: "AI-featured password managers" },
      { name: "Bitwarden", url: "https://bitwarden.com", license: "open-source", description: "Self-hostable password manager (disable AI vault features)", replaces: "AI password generators" },
      { name: "LessPass", url: "https://lesspass.com", license: "open-source", description: "Deterministic password generator — no database needed", replaces: "AI password tools" },
      { name: "pass", url: "https://passwordstore.org", license: "open-source", description: "Standard Unix password manager using GPG encryption", replaces: "AI-integrated auth managers" },
    ],
  },
  {
    id: "file-sync",
    name: "File Sync & Storage",
    icon: "☁️",
    description: "File storage and synchronization without AI organization or AI features",
    apps: [
      { name: "Syncthing", url: "https://syncthing.net", license: "open-source", description: "Peer-to-peer file sync without cloud dependency", replaces: "Dropbox AI, Google Drive AI" },
      { name: "Nextcloud", url: "https://nextcloud.com", license: "open-source", description: "Self-hosted cloud storage (use without AI apps)", replaces: "Google Drive AI, iCloud AI" },
      { name: "Rclone", url: "https://rclone.org", license: "open-source", description: "Command-line file sync for any cloud storage", replaces: "AI cloud management tools" },
      { name: "FreeFileSync", url: "https://freefilesync.org", license: "open-source", description: "Folder comparison and file synchronization tool", replaces: "AI-organized file systems" },
      { name: "Seafile", url: "https://seafile.com", license: "open-source", description: "Cloud file sync with client-side encryption", replaces: "Google Drive AI, OneDrive AI" },
    ],
  },
  {
    id: "audio-editing",
    name: "Audio Editing",
    icon: "🎵",
    description: "Audio editors using manual controls — no AI separation or generation",
    apps: [
      { name: "Audacity", url: "https://audacityteam.org", license: "open-source", description: "Multi-track audio editor and recorder", replaces: "AI audio tools, Adobe Podcast AI" },
      { name: "LMMS", url: "https://lmms.io", license: "open-source", description: "Digital audio workstation for music production", replaces: "AI music generators" },
      { name: "MuseScore", url: "https://musescore.org", license: "open-source", description: "Music notation software for composing and scoring", replaces: "AI composition tools" },
      { name: "Ardour", url: "https://ardour.org", license: "open-source", description: "Professional DAW for recording and mixing", replaces: "AI mastering services" },
      { name: "Tenacity", url: "https://tenacityaudio.org", license: "open-source", description: "Audacity fork focused on privacy, no telemetry", replaces: "AI audio processing tools" },
    ],
  },
  {
    id: "maps",
    name: "Maps & Navigation",
    icon: "🗺️",
    description: "Mapping tools without AI routing, AI recommendations, or AI features",
    apps: [
      { name: "OpenStreetMap", url: "https://openstreetmap.org", license: "open-source", description: "Community-built map of the world, no AI data", replaces: "Google Maps AI, Apple Maps AI" },
      { name: "OsmAnd", url: "https://osmand.net", license: "open-source", description: "Offline maps with turn-by-turn navigation", replaces: "Google Maps AI routing" },
      { name: "Organic Maps", url: "https://organicmaps.app", license: "open-source", description: "Privacy-friendly offline maps app", replaces: "AI-recommendation maps" },
      { name: "QMapShack", url: "https://github.com/Maproom/qmapshack", license: "open-source", description: "Planning and management of GPS routes", replaces: "AI route planning" },
      { name: "Marble", url: "https://marble.kde.org", license: "open-source", description: "KDE virtual globe and world atlas", replaces: "Google Earth AI features" },
    ],
  },
];
